// Mocks generated by Mockito 5.4.5 from annotations
// in flowery_e_commerce/test/features/address_details/domain/use_cases/add_address_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery_e_commerce/core/networking/common/api_result.dart'
    as _i4;
import 'package:flowery_e_commerce/features/address_details/domain/contracts/add_address_repo.dart'
    as _i2;
import 'package:flowery_e_commerce/features/address_details/domain/entities/request/add_address_request_entity.dart'
    as _i6;
import 'package:flowery_e_commerce/features/address_details/domain/entities/response/add_address_response_entity.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AddAddressRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddAddressRepo extends _i1.Mock implements _i2.AddAddressRepo {
  MockAddAddressRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.DataResult<_i5.AddAddressResponseEntity>> addAddress(
    _i6.AddAddressRequestEntity? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addAddress, [request]),
            returnValue:
                _i3.Future<_i4.DataResult<_i5.AddAddressResponseEntity>>.value(
                  _i7.dummyValue<_i4.DataResult<_i5.AddAddressResponseEntity>>(
                    this,
                    Invocation.method(#addAddress, [request]),
                  ),
                ),
          )
          as _i3.Future<_i4.DataResult<_i5.AddAddressResponseEntity>>);
}
