// Mocks generated by Mockito 5.4.4 from annotations
// in flowery_e_commerce/test/features/auth/data/data_sources/impl/auth_online_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:flowery_e_commerce/core/networking/api/api_manager.dart'
    as _i10;
import 'package:flowery_e_commerce/features/auth/data/models/request/forget_password_request_dto.dart'
    as _i14;
import 'package:flowery_e_commerce/features/auth/data/models/request/login_request_dto.dart'
    as _i12;
import 'package:flowery_e_commerce/features/auth/data/models/request/reset_password_request_dto.dart'
    as _i16;
import 'package:flowery_e_commerce/features/auth/data/models/request/signup_request_dto.dart'
    as _i13;
import 'package:flowery_e_commerce/features/auth/data/models/request/verify_reset_code_request_dto.dart'
    as _i15;
import 'package:flowery_e_commerce/features/auth/data/models/response/forget_password_response_dto.dart'
    as _i4;
import 'package:flowery_e_commerce/features/auth/data/models/response/login_response_dto.dart'
    as _i2;
import 'package:flowery_e_commerce/features/auth/data/models/response/reset_password_response_dto.dart'
    as _i6;
import 'package:flowery_e_commerce/features/auth/data/models/response/signup_response_dto.dart'
    as _i3;
import 'package:flowery_e_commerce/features/auth/data/models/response/verify_reset_code_response.dart'
    as _i5;
import 'package:flowery_e_commerce/features/categories/data/models/response/get_all_categories_response_dto.dart'
    as _i8;
import 'package:flowery_e_commerce/features/categories/data/models/response/get_all_products_rsponse_dto.dart'
    as _i9;
import 'package:flowery_e_commerce/features/generic/data/models/generic_response_dto.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponseDto_0 extends _i1.SmartFake
    implements _i2.LoginResponseDto {
  _FakeLoginResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignUpResponseDto_1 extends _i1.SmartFake
    implements _i3.SignUpResponseDto {
  _FakeSignUpResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgetPasswordResponseDto_2 extends _i1.SmartFake
    implements _i4.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyResetCodeResponseDto_3 extends _i1.SmartFake
    implements _i5.VerifyResetCodeResponseDto {
  _FakeVerifyResetCodeResponseDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResponseDto_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenericResponseDto_5 extends _i1.SmartFake
    implements _i7.GenericResponseDto {
  _FakeGenericResponseDto_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetAllCategoriesResponseDto_6 extends _i1.SmartFake
    implements _i8.GetAllCategoriesResponseDto {
  _FakeGetAllCategoriesResponseDto_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetAllProductsRsponseDto_7 extends _i1.SmartFake
    implements _i9.GetAllProductsRsponseDto {
  _FakeGetAllProductsRsponseDto_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManager extends _i1.Mock implements _i10.ApiManager {
  MockApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.LoginResponseDto> login(_i12.LoginRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue:
            _i11.Future<_i2.LoginResponseDto>.value(_FakeLoginResponseDto_0(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i11.Future<_i2.LoginResponseDto>);

  @override
  _i11.Future<_i3.SignUpResponseDto> signUp(_i13.SignUpRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [request],
        ),
        returnValue:
            _i11.Future<_i3.SignUpResponseDto>.value(_FakeSignUpResponseDto_1(
          this,
          Invocation.method(
            #signUp,
            [request],
          ),
        )),
      ) as _i11.Future<_i3.SignUpResponseDto>);

  @override
  _i11.Future<_i4.ForgetPasswordResponseDto> forgetPassword(
          _i14.ForgetPasswordRequestDto? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [request],
        ),
        returnValue: _i11.Future<_i4.ForgetPasswordResponseDto>.value(
            _FakeForgetPasswordResponseDto_2(
          this,
          Invocation.method(
            #forgetPassword,
            [request],
          ),
        )),
      ) as _i11.Future<_i4.ForgetPasswordResponseDto>);

  @override
  _i11.Future<_i5.VerifyResetCodeResponseDto> verifyResetCode(
          _i15.VerifyResetCodeRequestDto? resetCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [resetCode],
        ),
        returnValue: _i11.Future<_i5.VerifyResetCodeResponseDto>.value(
            _FakeVerifyResetCodeResponseDto_3(
          this,
          Invocation.method(
            #verifyResetCode,
            [resetCode],
          ),
        )),
      ) as _i11.Future<_i5.VerifyResetCodeResponseDto>);

  @override
  _i11.Future<_i6.ResetPasswordResponseDto> resetPassword(
          _i16.ResetPasswordRequestDto? resetPassword) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [resetPassword],
        ),
        returnValue: _i11.Future<_i6.ResetPasswordResponseDto>.value(
            _FakeResetPasswordResponseDto_4(
          this,
          Invocation.method(
            #resetPassword,
            [resetPassword],
          ),
        )),
      ) as _i11.Future<_i6.ResetPasswordResponseDto>);

  @override
  _i11.Future<_i7.GenericResponseDto> getGenericProduct(String? resourceName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGenericProduct,
          [resourceName],
        ),
        returnValue:
            _i11.Future<_i7.GenericResponseDto>.value(_FakeGenericResponseDto_5(
          this,
          Invocation.method(
            #getGenericProduct,
            [resourceName],
          ),
        )),
      ) as _i11.Future<_i7.GenericResponseDto>);

  @override
  _i11.Future<_i8.GetAllCategoriesResponseDto> getAllCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [],
        ),
        returnValue: _i11.Future<_i8.GetAllCategoriesResponseDto>.value(
            _FakeGetAllCategoriesResponseDto_6(
          this,
          Invocation.method(
            #getAllCategories,
            [],
          ),
        )),
      ) as _i11.Future<_i8.GetAllCategoriesResponseDto>);

  @override
  _i11.Future<_i9.GetAllProductsRsponseDto> getAllProducts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [],
        ),
        returnValue: _i11.Future<_i9.GetAllProductsRsponseDto>.value(
            _FakeGetAllProductsRsponseDto_7(
          this,
          Invocation.method(
            #getAllProducts,
            [],
          ),
        )),
      ) as _i11.Future<_i9.GetAllProductsRsponseDto>);
}
