// Mocks generated by Mockito 5.4.4 from annotations
// in flowery_e_commerce/test/features/best_seller/presentation/cubit/most_selling_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowery_e_commerce/core/networking/common/api_result.dart'
    as _i5;
import 'package:flowery_e_commerce/features/best_seller/domain/entities/most_selling_entity.dart'
    as _i6;
import 'package:flowery_e_commerce/features/best_seller/domain/repositories/most_selling_products_repository.dart'
    as _i2;
import 'package:flowery_e_commerce/features/best_seller/domain/use_cases/most_selling_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMostSellingProductsRepository_0 extends _i1.SmartFake
    implements _i2.MostSellingProductsRepository {
  _FakeMostSellingProductsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MostSellingProductsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMostSellingProductsUseCase extends _i1.Mock
    implements _i3.MostSellingProductsUseCase {
  MockMostSellingProductsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MostSellingProductsRepository get mostSellingProductsRepository =>
      (super.noSuchMethod(
        Invocation.getter(#mostSellingProductsRepository),
        returnValue: _FakeMostSellingProductsRepository_0(
          this,
          Invocation.getter(#mostSellingProductsRepository),
        ),
      ) as _i2.MostSellingProductsRepository);

  @override
  set mostSellingProductsRepository(
          _i2.MostSellingProductsRepository? _mostSellingProductsRepository) =>
      super.noSuchMethod(
        Invocation.setter(
          #mostSellingProductsRepository,
          _mostSellingProductsRepository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.DataResult<List<_i6.MostSellingProducts>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i5.DataResult<List<_i6.MostSellingProducts>>>.value(
                _i7.dummyValue<_i5.DataResult<List<_i6.MostSellingProducts>>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i5.DataResult<List<_i6.MostSellingProducts>>>);
}
